[tool.poetry]
name = "ptradesim"
version = "0.1.0"
description = "A Python simulator for the PTrade strategy framework."
authors = ["Kay <kay@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "ptradeSim" }]

[tool.poetry.dependencies]
python = ">=3.10.0,<4.0.0"
pandas = ">=2.3.0,<3.0.0"
matplotlib = ">=3.10.3,<4.0.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.7"
pytest = "^8.2.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
